/**
 * Géographie pour la saisie d'une paroisse : pays → région → ville → quartier.
 * Le Cameroun est le pays par défaut et le seul à avoir des listes détaillées ; pour les autres
 * pays (et pour tout ce qui manque), l'utilisateur saisit lui-même le texte.
 * Les listes de villes et surtout de quartiers sont volontairement partielles : elles couvrent
 * les principales localités et peuvent être complétées ici sans toucher au reste du code.
 */

export const DEFAULT_COUNTRY = 'Cameroun';

/** Pays proposés (noms français). Le Cameroun est en tête. */
export const COUNTRIES = [
  'Cameroun',
  'Afrique du Sud',
  'Algérie',
  'Allemagne',
  'Angola',
  'Belgique',
  'Bénin',
  'Brésil',
  'Burkina Faso',
  'Burundi',
  'Canada',
  'Centrafrique',
  'Congo',
  "Côte d'Ivoire",
  'Espagne',
  'États-Unis',
  'France',
  'Gabon',
  'Ghana',
  'Guinée',
  'Guinée équatoriale',
  'Italie',
  'Luxembourg',
  'Mali',
  'Maroc',
  'Niger',
  'Nigeria',
  'Pays-Bas',
  'Portugal',
  'République démocratique du Congo',
  'Royaume-Uni',
  'Rwanda',
  'Sénégal',
  'Suisse',
  'Tchad',
  'Togo',
  'Tunisie',
] as const;

/** Régions du Cameroun et leurs principales villes (chefs-lieux de départements et villes importantes). */
export const CAMEROON_REGIONS: Record<string, readonly string[]> = {
  Adamaoua: ['Ngaoundéré', 'Meiganga', 'Tibati', 'Tignère', 'Banyo', 'Bélel', 'Ngaoundal'],
  Centre: [
    'Yaoundé',
    'Mbalmayo',
    'Obala',
    'Bafia',
    'Mbandjock',
    'Nanga-Eboko',
    'Akonolinga',
    'Ntui',
    'Eséka',
    'Monatélé',
    'Ayos',
    'Mfou',
    'Saa',
    'Nkoteng',
    'Soa',
    'Okola',
    'Ngoumou',
    'Bokito',
    'Mbankomo',
  ],
  Est: [
    'Bertoua',
    'Batouri',
    'Abong-Mbang',
    'Yokadouma',
    'Garoua-Boulaï',
    'Lomié',
    'Bélabo',
    'Doumé',
    'Moloundou',
    'Betaré-Oya',
  ],
  'Extrême-Nord': [
    'Maroua',
    'Kousséri',
    'Mokolo',
    'Yagoua',
    'Mora',
    'Kaélé',
    'Bogo',
    'Maga',
    'Meri',
    'Tokombéré',
    'Mindif',
    'Guidiguis',
    'Fotokol',
    'Waza',
  ],
  Littoral: [
    'Douala',
    'Nkongsamba',
    'Edéa',
    'Loum',
    'Mbanga',
    'Penja',
    'Dizangué',
    'Manjo',
    'Yabassi',
    'Melong',
    'Mouanko',
    'Njombé',
  ],
  Nord: [
    'Garoua',
    'Guider',
    'Figuil',
    'Poli',
    'Tcholliré',
    'Rey-Bouba',
    'Lagdo',
    'Pitoa',
    'Touboro',
    'Mayo-Oulo',
  ],
  'Nord-Ouest': [
    'Bamenda',
    'Kumbo',
    'Wum',
    'Mbengwi',
    'Nkambé',
    'Fundong',
    'Bali',
    'Ndop',
    'Bafut',
    'Batibo',
    'Jakiri',
  ],
  Ouest: [
    'Bafoussam',
    'Dschang',
    'Mbouda',
    'Foumban',
    'Bafang',
    'Bangangté',
    'Foumbot',
    'Bandjoun',
    'Baham',
    'Bazou',
    'Kékem',
    'Bangou',
  ],
  Sud: [
    'Ebolowa',
    'Kribi',
    'Sangmélima',
    'Ambam',
    'Lolodorf',
    'Djoum',
    'Campo',
    'Mvangan',
    'Akom II',
    'Meyomessala',
  ],
  'Sud-Ouest': [
    'Buéa',
    'Limbé',
    'Kumba',
    'Mamfe',
    'Tiko',
    'Mutengene',
    'Muyuka',
    'Idenau',
    'Bangem',
    'Fontem',
    'Mundemba',
  ],
};

/** Quartiers connus, par ville. Une ville absente de cette table se saisit à la main. */
export const CAMEROON_DISTRICTS: Record<string, readonly string[]> = {
  Yaoundé: [
    'Ahala',
    'Awae',
    'Bastos',
    'Biteng',
    'Biyem-Assi',
    'Briqueterie',
    'Carrière',
    'Centre administratif',
    'Cité Verte',
    'Djoungolo',
    'Efoulan',
    'Ekounou',
    'Ekoudou',
    'Elig-Edzoa',
    'Elig-Essono',
    'Emana',
    'Essos',
    'Etoudi',
    'Hippodrome',
    'Kondengui',
    'Madagascar',
    'Melen',
    'Mendong',
    'Messa',
    'Mfandena',
    'Mimboman',
    'Mokolo',
    'Mvan',
    'Mvog-Ada',
    'Mvog-Betsi',
    'Mvog-Mbi',
    'Mvolyé',
    'Ngoa-Ekellé',
    'Ngousso',
    'Nkolbisson',
    'Nkolndongo',
    'Nkomkana',
    'Nlongkak',
    'Nsam',
    'Nsimeyong',
    'Obili',
    'Obobogo',
    'Odza',
    'Olezoa',
    'Oyom-Abang',
    'Santa Barbara',
    'Simbock',
    'Tsinga',
  ],
  Douala: [
    'Akwa',
    'Akwa Nord',
    'Bali',
    'Bepanda',
    'Bassa',
    'Bonabéri',
    'Bonamoussadi',
    'Bonanjo',
    'Bonapriso',
    'Bonendale',
    'Brazzaville',
    'Cité des Palmiers',
    'Cité SIC',
    'Dakar',
    'Deïdo',
    'Japoma',
    'Kassalafam',
    'Kotto',
    'Logbaba',
    'Logbessou',
    'Logpom',
    'Makepe',
    'Mbanya',
    'New Bell',
    'Ndogbong',
    'Ndokotti',
    'Ndogpassi',
    'Nkongmondo',
    'Nylon',
    'Oyack',
    'PK 8',
    'PK 10',
    'PK 14',
    'Village',
    'Yassa',
    'Youpwé',
  ],
  Bafoussam: [
    'Banengo',
    'Djeleng',
    'Famla',
    'Haoussa',
    'Kamkop',
    'Lafé-Baleng',
    'Ndiengdam',
    'Tamdja',
    'Tougang',
  ],
  Bamenda: [
    'Azire',
    'Bamendakwe',
    'Bambili',
    'Commercial Avenue',
    'Mankon',
    'Mile 3 Nkwen',
    'Mile 4 Nkwen',
    'Mulang',
    'Ntamulung',
    'Ntarikon',
    'Nkwen',
    'Old Town',
    'Up Station',
  ],
  Garoua: [
    'Bibémiré',
    'Djamboutou',
    'Foulbéré',
    'Lopéré',
    'Marouaré',
    'Nassarao',
    'Ouro-Tchédé',
    'Pitoaré',
    'Plateau',
    'Poumpoumré',
    'Roumdé Adjia',
    'Yelwa',
  ],
  Maroua: [
    'Dougoï',
    'Domayo',
    'Doualaré',
    'Founangué',
    'Hardé',
    'Kakataré',
    'Makabaye',
    'Meskine',
    'Ouro-Tchédé',
    'Palar',
    'Pont Vert',
    'Salak',
    'Zokok',
  ],
  Ngaoundéré: [
    'Baladji',
    'Bamyanga',
    'Burkina',
    'Dang',
    'Gada Mabanga',
    'Haoussa',
    'Joli Soir',
    'Mbibaré',
    'Mbideng',
    'Norvégien',
    'Sabongari',
  ],
  Bertoua: [
    'Bofia',
    'Enia',
    'Haoussa',
    'Kano',
    'Kpokolota',
    'Mandjou',
    'Mokolo',
    'Ndemba',
    'Nkolbikon',
    'Tigaza',
  ],
  Buéa: [
    'Bokwaongo',
    'Bomaka',
    'Bonduma',
    'Bwitingi',
    'Check Point',
    'Clerks Quarters',
    'Great Soppo',
    'Molyko',
    'Muea',
    'Small Soppo',
  ],
  Limbé: [
    'Batoke',
    'Bota',
    'Church Street',
    'Down Beach',
    'Middle Farms',
    'Mile 4',
    'Mbonjo',
    'New Town',
  ],
  Kumba: ['Barombi', 'Buea Road', 'Fiango', 'Kosala', 'Mambanda', 'Mbonge Road', 'Three Corners'],
  Kribi: ['Afan Mabe', 'Dombé', 'Elabé', 'Mpalla', 'Mpolongwé', 'Ngoyé', 'Talla'],
};

export const regionsOf = (country: string): string[] =>
  country === DEFAULT_COUNTRY ? Object.keys(CAMEROON_REGIONS) : [];

export const citiesOf = (country: string, region: string): string[] =>
  country === DEFAULT_COUNTRY ? [...(CAMEROON_REGIONS[region] ?? [])] : [];

export const districtsOf = (country: string, city: string): string[] =>
  country === DEFAULT_COUNTRY ? [...(CAMEROON_DISTRICTS[city] ?? [])] : [];

/**
 * Noms anglais des pays et des régions. La valeur enregistrée en base reste le nom français (identité
 * stable) : seul l'affichage est traduit. Un nom absent de la table (saisie libre) est rendu tel quel.
 */
const COUNTRY_NAMES_EN: Record<string, string> = {
  Cameroun: 'Cameroon',
  'Afrique du Sud': 'South Africa',
  Algérie: 'Algeria',
  Allemagne: 'Germany',
  Belgique: 'Belgium',
  Bénin: 'Benin',
  Brésil: 'Brazil',
  Centrafrique: 'Central African Republic',
  "Côte d'Ivoire": 'Ivory Coast',
  Espagne: 'Spain',
  'États-Unis': 'United States',
  Guinée: 'Guinea',
  'Guinée équatoriale': 'Equatorial Guinea',
  Italie: 'Italy',
  Maroc: 'Morocco',
  'Pays-Bas': 'Netherlands',
  'République démocratique du Congo': 'Democratic Republic of the Congo',
  'Royaume-Uni': 'United Kingdom',
  Sénégal: 'Senegal',
  Suisse: 'Switzerland',
  Tchad: 'Chad',
  Tunisie: 'Tunisia',
};

const REGION_NAMES_EN: Record<string, string> = {
  Est: 'East',
  'Extrême-Nord': 'Far North',
  Nord: 'North',
  'Nord-Ouest': 'North-West',
  Ouest: 'West',
  Sud: 'South',
  'Sud-Ouest': 'South-West',
};

const byLocale = (table: Record<string, string>, name: string, locale: string): string =>
  locale === 'en' ? (table[name] ?? name) : name;

/** Nom d'un pays dans la langue demandée (`fr` : tel qu'enregistré). */
export const countryLabel = (country: string, locale: string): string =>
  byLocale(COUNTRY_NAMES_EN, country, locale);

/** Nom d'une région du Cameroun dans la langue demandée. */
export const regionLabel = (region: string, locale: string): string =>
  byLocale(REGION_NAMES_EN, region, locale);
