export enum ContentType {
  SONG = 'SONG',
  PSALM = 'PSALM',
  GOSPEL = 'GOSPEL',
  READING = 'READING',
  PRAYER = 'PRAYER',
  UNIVERSAL_PRAYER = 'UNIVERSAL_PRAYER',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  FREE_TEXT = 'FREE_TEXT',
}
